[package]
name = "version"
version = "0.1.9"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.56"
chrono = "0.4.19"
common = { path = "../common" }
simplelog = "0.11.2"
directories = "4.0.1"
log = "0.4.14"
forward-dll = "0.1.4"
